set fenc=utf-8
set showcmd
set number
set cursorline
set virtualedit=onemore
set smartindent
set showmatch
set laststatus=2
set expandtab
set tabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set wrapscan
set hlsearch
set list
set listchars=tab:≫-,trail:_,eol:↲,extends:≫,precedes:≪,nbsp:%
let g:netrw_altv=1
let g:netrw_liststyle=3
syntax on
